### PR TITLE
implement ui and storage

### PR DESCRIPTION
**Pull request by seanl-adg**
This is not ready for merging.
`gulp dev` will build a userscript that is testable.
`gulp beta` will build a minified userscript that needs to be tested too.

Notes:
 - [x] Notification from cross-origin child iframe: tested on Chrome Tampermonkey, FF Greasemonkey
   - Create an empty page which loads a website that is known to have popups as an iframe, and try clicking on the iframe. It should show a notification on the top frame.
   - At the moment, this cannot work correctly on AG for Win, due to a bug https://github.com/AdguardTeam/AdguardForWindows/issues/1892.
 - [x] Fallback to not showing in-iframe notifications when `WeakMap` is not available.
 - [x] There should be a css animation effect on iframe elements so that it appears and moves smoothly.
 - [x] When an alert is closed by clicking on its close button, other alerts stacked below it should be pushed up.

### CODE REVIEW

**Comment by ameshkov** [comment]
> There should be a settings page so that users can manage whitelisted domains.

We don't need it right now.

Don't make tasks THAT GLOBAL, it makes it too hard to review complicated things.
Instead do it step by step, one single thing after another.

**Comment by ameshkov** [comment]
Every checkbox in your list should be a separate GH issue with a separate pull request.

Moreover, for the second release, we need nothing of it -- it'd be enough to have alerts in the main frame and silent suppression of pop-ups in the nested frames.

**Comment by seanl-adg** [comment]
At least we should provide a way that a user can revert whitelisted domains. Could you please provide idea on how this should be done in a less global way?

**Comment by ameshkov** [comment]
> At least we should provide a way that a user can revert whitelisted domains. This is needed for 2.1 
version. Could you please provide idea on how this should be done in a less global way?

Reinstall in AG cleans the GM properties, which is ok as a temporary solution until we come up with better UI.

**Comment by seanl-adg** [comment]
@ameshkov Here https://github.com/AdguardTeam/PopupBlocker/blob/feature/issues/13/src/ui/show-alert.ts#L70 `requestAnimationFrame` is not supported on IE9, should I add a polyfill?

**Comment by ameshkov** [comment]
@seanl-adg I am quite sure that we should make this userscript support IE11+

**Comment by seanl-adg** [comment]
Just for a reference, currently most of functionality works on IE10.

**Pull request merged**
