### PR TITLE
Fix for OUJS

### PR DESCRIPTION
**Pull request by Martii**
Hope this is the right place... looks like you dynamically create the .user.js script. :smile:

OUJS has made a change recently to require SPDX codes for OSI approved licensing.

In order to improve the appearance of your script homepage it would be appreciated if you could modify your affected script here.

Until this change is made you will be unable to update those affected scripts.

Thanks,
OUJS Staff

### CODE REVIEW

**Comment by ameshkov** [comment]
@Martii thank you!

@seanl-adg could you please check if this PR is enough?

**Comment by Martii** [comment]
Welcome. :) The only reason why I mentioned if it was the right place is because [/AdguardTeam/PopupBlocker/blob/`528cdab`/package.json#L10](https://github.com/AdguardTeam/PopupBlocker/blob/528cdab513bec9c2e661e0590b500abb5da86ac0/package.json#L10) says it's `MIT` SPDX short identifier for a package instead of the .user.js. I assume this is distributed somewhere else due to this under a different license?

**Comment by ameshkov** [comment]
@Martii not really, it seems we have a mistake there:)

**Comment by Martii** [comment]
I can add that too. :) Just takes a moment.

**Comment by Martii** [comment]
Thanks.... look forward to it in the wild on OUJS. :)

**Pull request merged**
